### ISSUE TITLE
requiresMainQueueSetup Warning

### ISSUE THREAD

**Issue by heckchuckman** [wix/react-native-paged-contacts#16]
Hi,

Thanks for this module. Great work!

I'm getting the following debugger error:

> RCTLog.js:48 Module RCTPagedContactsModule requires main queue setup since it overrides `constantsToExport` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

I looks like a fix similar to https://github.com/wix/react-native-navigation/pull/1983/files#diff-b8c48202d12fa78c4c377e5a3225c298 would do the trick, but my Obj C isn't the best to handle the update on my own.

Let me know if this is easily fixed for a future release.

Thanks again!

**Comment by LeoNatan** [comment]
@auval Please add the following code to the module.m file:

```
+ (BOOL)requiresMainQueueSetup
{
	return YES;
}
```

Just so we don't get crashes.

**Comment by auval** [comment]
@LeoNatan added

**Comment by LeoNatan** [comment]
Great!

**Comment by heckchuckman** [comment]
Awesome. Thank you both!
