### ISSUE TITLE
remove CNContactPhoneticOrganizationNameKey

### ISSUE THREAD

**Issue by Vasiliev90** [wix/react-native-paged-contacts#6]
Could you make a version without this 3 lines, because I got a failed build with it?

<img width="926" alt="2017-02-23 09 20 10" src="https://cloud.githubusercontent.com/assets/6060112/23248710/7f7fce56-f9a9-11e6-9e76-c79b77d4f37a.png">

**Comment by LeoNatan** [comment]
No. This is to ensure iOS 9 support. 

I have a feeling you are using Xcode 7. Xcode 7 is not supported. Please upgrade to Xcode 8.

**Comment by Vasiliev90** [comment]
Ok, thanks for fast reply.
